id: I4A25280F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:46:02+00:00'
last_modified: '2022-06-08T08:34:07.659110+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6238
  title: རི་བོ་རྩེ་ལྔའི་གནས་ཡིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9FAA:
      image_group_id: I1KG1241
      title: ''
      total_pages: 218
      order: 1
      base_file: 9FAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
