id: P009093
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ6238
  title: རི་བོ་རྩེ་ལྔའི་གནས་ཡིག་
  author: ''
  volumes:
    8a0f2e74c8824ba7a0b9197a39b6c96c:
      image_group_id: I1KG1241
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
